name: Sync Readme

on:
  push:
    branches:
      - 'main'
    paths:
      - '/charts/cbioportal/README.md'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cp -f /charts/cbioportal/README.md ${{ runner.temp }}/README.md
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - run: |
          cp -f ${{ runner.temp }}/README.md .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTION@users.noreply.github.com"
          git add README.md
          git commit --signoff -m "Sync README from main"
          git push